### ISSUE TITLE
generatejson.py number of parser arguments incorrect?

### ISSUE THREAD

**Issue by fortiko** [macadmins/installapplications#101]
Hello! Sorry if I missed something, but on line 237 of generatejson.py it says

`parser.add_argument('--item', default=None, action='append', nargs=6,`

but then the code proceeds to require 7 arguments:

item-name='A name' 
item-path='A path' 
item-stage='A stage' 
item-type='A type' 
item-url='A url' 
script-do-not-wait='A boolean' 
pkg-skip-if='A string' 

which for me leads to ValueError("length of metavar tuple does not match nargs"). 

If I updated nargs=7, the code works as expected and generates bootstrap.json in the output directory.

Should that be fixed or am I missing something here?

**Comment by erikng** [comment]
It could be a bug. I've merged some PRs lately that I personally haven't tested and trusted the author. If you have fixed it, please PR it and I'll merge.

**Comment by andrewzirkel** [comment]
I have it fixed in [100](https://github.com/macadmins/installapplications/pull/100) so you can reference that or merge that piece.

**Comment by erikng** [comment]
I fixed it. Thanks for the note.
