### ISSUE TITLE
Microsoft Intune MDM Compatibility

### ISSUE THREAD

**Issue by ataylor-orcsd-org** [macadmins/installapplications#75]
I've successfully used installapplications with Microsoft Intune.  I know there are some caveats, is it worth noting in the Wiki?  Our school gets it free so we have to use it over one of the other MDMs.

**Comment by natewalck** [comment]
I think that would be cool. Having a guide to outline what is necessary to use this with Intune could help folks get started.

**Comment by ataylor-orcsd-org** [comment]
What would be the preferred format for me to write that up?

**Comment by erikng** [comment]
Just add it to the wiki.

**Comment by ataylor-orcsd-org** [comment]
I have added the initial Wiki page.
