### ISSUE TITLE
Rosetta missing from Apple Silicon, and IAs launchdaemon fails.

### ISSUE THREAD

**Issue by chilcote** [macadmins/installapplications#80]
as titled. Related: https://github.com/macadmins/installapplications/pull/79

**Comment by erikng** [comment]
So the question is, what do we need Rosetta for?

1. Python as it is configured?
2. Will a "fat python bundle" work without Rosetta support?

**Comment by chilcote** [comment]
Yeah it's because python won't load and the LD crashes. Theoretically an arm64 build of python would solve this, but you'd possibly need Rosetta for the scripts and packages that IAs installs (chef, etc).

**Comment by erikng** [comment]
https://bugs.python.org/issue41100

**Comment by erikng** [comment]
I need testers for: https://github.com/macadmins/installapplications/pull/81

**Comment by erikng** [comment]
Nate has confirmed this is working on IAs 2.1. I'm considering this closed. If someone find that this is not true, please re-open/comment.
