### ISSUE TITLE
No module named 'Foundation' on M1

### ISSUE THREAD

**Issue by jstaubr** [macadmins/installapplications#89]
Hi,

I'm testing the latest universal commits on M1 and I'm getting 

```
Traceback (most recent call last):
  File "/Library/installapplications/installapplications.py", line 29, in <module>
    from Foundation import NSLog
ModuleNotFoundError: No module named 'Foundation'
```

Am I doing something wrong? If I install rosetta the 2.0.2 intel version works.

edit: 2.1 Alpha 1 also works so this might be only on the latest code.

**Comment by erikng** [comment]
I'm confused by your edit, but yes you must be using absolutely latest commit with the available python framework.

**Comment by jstaubr** [comment]
Sorry, I see now that the edit is a little weird.

What I meant to say was that the latest commit I used today with built python framework returned the above error.
When using 2.1 Alpha1 from december this does not occur.

**Comment by erikng** [comment]
That makes sense. Closing ticket.
