### ISSUE TITLE
Version 2.0.3 build-info.json version key is 2.1

### ISSUE THREAD

**Issue by percisely** [macadmins/installapplications#91]
`    "version": "2.1"`
should be
`    "version": "2.0.3"`
right?

**Comment by erikng** [comment]
Sorry about that. I originally was going to make it 2.1, but since there are no new features besides Apple Silicon support, I decided to make it 2.0.3. I forgot to change this file.

it's now fixed

**Comment by percisely** [comment]
Thanks!
